package fr.upem.matou.hmi;

import fr.upem.matou.client.IOConsumer;
import fr.upem.matou.client.Info;
import fr.upem.matou.common.Message;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.io.IOException;
import java.nio.file.Path;
import java.util.Objects;

/**
 * Private connection window.
 *
 * @author Damien Chesneau
 */
public class PrivateConnection extends JFrame {
    private final String targetPseudo;
    private final MessagesTableModel messagesTableModel;
    private final IOConsumer<Path> sendFile;
    private final IOConsumer<String> sendMessage;
    private JTable tableMessages;
    private JButton buttonSendMessage;
    private JTextArea writeMessage;
    private JButton sendFileButton;
    private JLabel connectedLabel;
    private JPanel root;

    PrivateConnection(String targetPseudo, IOConsumer<Path> sendFile) {
        this(null, targetPseudo, sendFile);
    }

    PrivateConnection(IOConsumer<String> sendMessage, String targetPseudo, IOConsumer<Path> sendFile) {
        this.targetPseudo = Objects.requireNonNull(targetPseudo);
        this.sendFile = (sendFile);
        this.sendMessage = (sendMessage);
        connectedLabel.setText(targetPseudo + " chat");
        setContentPane(root);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        pack();
        messagesTableModel = new MessagesTableModel();
        tableMessages.setModel(messagesTableModel);
        buttonSendMessage.addActionListener(this::onListenerNewMessage);
        sendFileButton.addActionListener(this::onListenerSendFile);
        setSize(620, 450);
        setTitle("Private chat");
        setResizable(false);
    }

    public void newMessage(String message) {
        Objects.requireNonNull(message);
        messagesTableModel.newMessage(new Message(targetPseudo, message));
    }

    public void onError(Info info) {
        Objects.requireNonNull(info);
        switch (info) {
            case CLIENT_ACCEPT_FILE:
                HmiTools.showInfo(this, "Remote client accept the transfer.");
                break;
            case CLIENT_REFUSE_FILE:
                HmiTools.showInfo(this, "Remote client refuse the transfer.");
                break;
            case ILLEGAL_SECURE_NUMBER:
                HmiTools.showInfo(this, "We can't establish the connection.");
                break;
            case TRANSFER_COMPLETED:
                HmiTools.showInfo(this, "File transfer finish.");
                break;
            default:
                throw new AssertionError();
        }
    }

    private void onListenerSendFile(ActionEvent l) {
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.showDialog(this, "Choose our file to send");
        Path path = jFileChooser.getSelectedFile().toPath();
        try {
            sendFile.accept(path);
        } catch (IOException e) {
            HmiTools.showError(this, "Can't send file request.");
        }
    }

    private void onListenerNewMessage(ActionEvent l) {
        String text = writeMessage.getText();
        writeMessage.setText("");
        messagesTableModel.newMessage(new Message("My self", text));
        try {
            sendMessage.accept(text);
        } catch (IOException e) {
            e.printStackTrace();
            System.err.println(e.getMessage());
            HmiTools.showError(e.getMessage());
        }
    }

    boolean askIfUserWhatAskedFile(String fileName) {
        return HmiTools.doChoice(this, "Do you want to get " + fileName + " file ? ", "Remote user wan't to send you a file.");
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root = new JPanel();
        root.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        panel1.setPreferredSize(new Dimension(435, 500));
        panel1.setRequestFocusEnabled(true);
        root.add(panel1, BorderLayout.EAST);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        panel2.setPreferredSize(new Dimension(450, 300));
        panel2.setRequestFocusEnabled(false);
        panel1.add(panel2, BorderLayout.NORTH);
        tableMessages = new JTable();
        panel2.add(tableMessages, BorderLayout.CENTER);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new BorderLayout(0, 0));
        panel3.setPreferredSize(new Dimension(450, 100));
        panel3.setRequestFocusEnabled(false);
        panel1.add(panel3, BorderLayout.SOUTH);
        buttonSendMessage = new JButton();
        buttonSendMessage.setLabel("Send");
        buttonSendMessage.setText("Send");
        panel3.add(buttonSendMessage, BorderLayout.EAST);
        writeMessage = new JTextArea();
        panel3.add(writeMessage, BorderLayout.CENTER);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new BorderLayout(0, 0));
        panel1.add(panel4, BorderLayout.CENTER);
        final JLabel label1 = new JLabel();
        label1.setText("Enter our message in this box :");
        panel4.add(label1, BorderLayout.CENTER);
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new BorderLayout(0, 0));
        root.add(panel5, BorderLayout.WEST);
        connectedLabel = new JLabel();
        connectedLabel.setText("Connected with :");
        panel5.add(connectedLabel, BorderLayout.NORTH);
        sendFileButton = new JButton();
        sendFileButton.setText("Send file");
        panel5.add(sendFileButton, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }
}
